replicaCount: 2
image:
  repository: ghcr.io/kadekchresna/order-service
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8081

resources:
  limits:
    memory: "128Mi"
    cpu: "250m"

livenessProbe:
  path: /healthz
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  path: /healthz
  initialDelaySeconds: 5
  periodSeconds: 10

postgresql:
  enabled: true
  auth:
    username: ordersvc
    password: ordersvcpass
    database: orderdb
  architecture: standalone
  primary:
    persistence:
      enabled: true
      size: 1Gi
      storageClass: standard

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 512Mi
      storageClass: standard
