replicaCount: 2
image:
  repository: ghcr.io/kadekchresna/order-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8081

resources:
  limits:
    memory: "128Mi"
    cpu: "250m"

livenessProbe:
  path: /api/v1/healthz
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  path: /api/v1/healthz
  initialDelaySeconds: 5
  periodSeconds: 10

postgresql:
  auth:
    password: ""
    username: oms
    database: omsdb
    existingSecret: "order-service-postgresql"
  primary:
    persistence:
      enabled: true
      size: 2Gi
      storageClass: "standard"
  service:
    type: ClusterIP
    port: 5432

redis:
  auth:
    enabled: false
  architecture: standalone
  master:
    persistence:
      enabled: true
      size: 1Gi
      storageClass: "standard"
  service:
    type: ClusterIP
    port: 6379
