# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: { { include (print .Chart.Name ".fullname") . } }
  labels:
    app: { { include (print .Chart.Name ".name") . } }
spec:
  type: { { .Values.service.type } }
  selector:
    app: { { include (print .Chart.Name ".name") . } }
  ports:
    - protocol: TCP
      port: { { .Values.service.port } }
      targetPort: { { .Values.service.targetPort } }
