replicaCount: 2
image:
  repository: ghcr.io/kadekchresna/shop-service
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 8081
resources:
  limits:
    memory: "64Mi"
    cpu: "125m"
livenessProbe:
  path: /api/v1/healthz
  initialDelaySeconds: 15
  periodSeconds: 20
readinessProbe:
  path: /api/v1/healthz
  initialDelaySeconds: 5
  periodSeconds: 10

postgresql:
  auth:
    password: ""
    username: shopsvc
    database: shopdb
    existingSecret: "shop-service-postgresql"
  primary:
    persistence:
      enabled: true
      size: 2Gi
      storageClass: "standard"
  service:
    type: ClusterIP
    port: 5432
