apiVersion: v1
kind: Service
metadata:
  name: {{ include "shop-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "shop-service.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "shop-service.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
