replicaCount: 2
image:
  repository: ghcr.io/kadekchresna/warehouse-service
  tag: v1
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 8081
resources:
  limits:
    memory: "128Mi"
    cpu: "250m"
livenessProbe:
  path: /healthz
  initialDelaySeconds: 15
  periodSeconds: 20
readinessProbe:
  path: /healthz
  initialDelaySeconds: 5
  periodSeconds: 10
