apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "order-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "order-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "order-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "order-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./order-service"]
          args: ["web"]
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory | quote }}
              cpu: {{ .Values.resources.limits.cpu | quote }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds:
              {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds:
              {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          env:
            - name: DB_DSN
              value: >-
                postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@{{ .Release.Name }}-postgresql:5432/$(POSTGRES_DB)?sslmode=disable
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include (print .Chart.Name ".fullname") . }}-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-service-postgresql
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include (print .Chart.Name ".fullname") . }}-secret
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              value: "{{ .Release.Name }}-postgresql"
            - name: KAFKA_URL
              value: "kafka:9092"
            - name: REDIS_URL
              value: {{ .Release.Name }}-redis-master:6379
            - name: APP_NAME
              value: order
            - name: APP_ENV
              value: prd
            - name: APP_PORT
              value: "8081"
            - name: APP_STATIC_TOKEN
              value: secret
            - name: APP_JWT_SECRET
              value: secret
        - name: {{ .Chart.Name }}-consumer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./order-service"]
          args: ["consumer"]
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory | quote }}
              cpu: {{ .Values.resources.limits.cpu | quote }}
          env:
            - name: DB_DSN
              value: >-
                postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@{{ .Release.Name }}-postgresql:5432/$(POSTGRES_DB)?sslmode=disable
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include (print .Chart.Name ".fullname") . }}-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-service-postgresql
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include (print .Chart.Name ".fullname") . }}-secret
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              value: "{{ .Release.Name }}-postgresql"
            - name: KAFKA_URL
              value: "kafka:9092"
            - name: REDIS_URL
              value: {{ .Release.Name }}-redis-master:6379
            - name: APP_NAME
              value: order
            - name: APP_ENV
              value: prd
            - name: APP_PORT
              value: "8081"
            - name: APP_STATIC_TOKEN
              value: secret
            - name: APP_JWT_SECRET
              value: secret