{{- if .Values.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include (print .Chart.Name ".fullname") . }}-secrets
  labels:
    app: {{ include (print .Chart.Name ".name") . }}
type: Opaque
stringData:
  postgres-user: {{ .Values.secrets.postgres.user }}
  postgres-password: {{ .Values.secrets.postgres.password }}
  postgres-database: {{ .Values.secrets.postgres.database }}
{{- end }}