fullnameOverride: kafka

auth:
  enabled: false
  clientProtocol: plaintext
  interBrokerProtocol: plaintext
  controllerProtocol: plaintext

kraft:
  enabled: true
  clusterId: "local-cluster-id"

controller:
  replicaCount: 1
broker:
  replicaCount: 1

config:
  process.roles: "controller,broker"
  node.id: 1
  controller.listener.names: "CONTROLLER"
  controller.quorum.voters: "1@localhost:9093"
  listeners: "PLAINTEXT://:9092,CONTROLLER://:9093"
  advertised.listeners: "PLAINTEXT://localhost:9092"
  listener.security.protocol.map: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
  auto.create.topics.enable: "true"

listeners:
  client:
    protocol: PLAINTEXT
    port: 9092

advertisedListeners:
  client:
    name: PLAINTEXT
    address: localhost
    port: 9092

externalAccess:
  enabled: false

persistence:
  enabled: false # <--- disable persistence to avoid mount issues

provisioning:
  enabled: false

service:
  type: ClusterIP
