apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-service.fullname" . }}-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-postgresql
type: Opaque
stringData:
  username: "usersvc"
  password: "usersvcpass"
  postgres-password: "usersvcpass"
  database: "userdb"
